### ISSUE TITLE
Fix component description

### ISSUE THREAD

**Issue by talimarcus** [PredixDev/px-toggle#1]
Update the auto-generated px-toggle description from "REPLACE THIS TEXT ..." (above Usage section)

![screen shot 2017-03-21 at 12 07 48 pm](https://cloud.githubusercontent.com/assets/9092541/24166346/2d9704e2-0e30-11e7-97df-8bec7be6ca08.png)

**Comment by randyaskin** [comment]
Fixed in v1.0.3.
