### ISSUE TITLE
webcomponentsjs lib upgraded, causing bower to not install cleanly 

### ISSUE THREAD

**Issue by donaldltrott** [PredixDev/px-toggle#6]
# Submit an Issue
The webcomponentsjs library released a new version so when you try to bower install this component you get a decision tree to choose what version you want to use. This is a problem when doing automated builds with Jenkins.

Possible solution could be to remove the `^` from the bower.json so that all the versions of dependencies used are specific and not variable

## Expected behavior and actual behavior:

The expected behavior is that this should install without any interactions after you run `bower install`. The actual behavior is that the bower install is interrupted and you have to choose which version to use

![region capture 1](https://user-images.githubusercontent.com/11775251/29878320-d46f9f5c-8d67-11e7-8a08-e961a75405ab.png)

## Steps to reproduce the problem:

To reproduce, start from a new project or delete your `bower_components` folder from your project. Run `bower install px-toggle --save`.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

All environments

**Comment by mdwragg** [comment]
Hi,
In the environment section you omitted the _component version number_. Can you let us know which version you are trying to install?

**Comment by mdwragg** [comment]
And our CI results for your interest showing passing releases (i.e. `bower install` completing successfully prior to running tests): https://travis-ci.org/PredixDev/px-toggle/branches.

Thanks.

**Comment by randyaskin** [comment]
Since v2, this component has contained a resolution for webcomponentsjs:
https://github.com/PredixDev/px-toggle/blob/master/bower.json#L39-L41

**Comment by donaldltrott** [comment]
was installing the latest which is v2.0.2

**Comment by gstroup** [comment]
I have also seen this issue with some px components using a new version of webcomponents.js.  It's not a problem when the component runs in isolation.  But it is a problem in an application where other components depend on the older version of the webcomponents.js shim.

**Comment by mdwragg** [comment]
That's just how bower works @gstroup - you have to resolve for the correct version of webcomponents js in your application bower.json file (0.7.x, in this case).

**Comment by mdwragg** [comment]
We had our hand forced here by the `hybrid` polymer components that support both the V0 and V1 web components standard (via Polymer 1.x and 2.x, respectively).

@donaldltrott - either add a resolution in your app or disable interactive mode for bower.

e.g. https://github.com/PredixDev/px-toggle/blob/master/bower.json#L40

👍

**Comment by gstroup** [comment]
Yes, I just added the resolution.  Not a big problem.
Now I understand why it popped up - those hybrid components.  Makes sense.  Thanks!

**Comment by donaldltrott** [comment]
@randyaskin  if you are going to resolve to a specific version shouldn't you be using 

"resolutions": {
    "webcomponentsjs": "0.7.24"
  }

without the `^` so that it pulls a specific version and not a newer version than the one resolved?

While working on FiledVision we ran into these same issues and had to remove all the `^` and `~` from the versions in the bower.json so that we controlled the exact versions that were used in our dependencies.

**Comment by randyaskin** [comment]
No, the main point for us is that ^0.7.24 resolves to the latest 0.x and does not pull in 1.0.2 (from your screenshot) that is associated with Polymer 2.0.

**Comment by mdwragg** [comment]
`~` = any patch release; e.g. 1.0.1, 1.0.2, 1.0.3 etc.
`^` = any minor release (non-api changing but additional features) e.g. 1.1.0, 1.2.0, 1.3.0.

Major version numbers signify API breaking changes e.g. 1.0.0, 2.0.0, 3.0.0.
